/**
 * Real backtest-proven swing symbols — the intersection gate for the
 * capacity-based pool in auto-trade/route.ts. Being highly RS-ranked
 * (momentum/relative-strength) is a real but separate signal from "this
 * specific stock's price action actually suits the swing rule-set" — the
 * options backtest found exactly this split (high-beta PSU names ranked
 * fine but lost badly), and the full-universe swing backtest below found
 * the same split.
 *
 * Auto-regenerated by scripts/refresh-swing-proven-symbols.mts on 2026-07-27
 * — real 1825-day, 500-stock full-NSE-universe swing backtest,
 * filtered to profitFactor > 1.4 AND totalTrades >= 15 (excludes both
 * weak performers and small-sample noise). Restricted-series (T2T)
 * symbols are cross-checked and excluded automatically at generation
 * time via symbol-series-check.ts (same live Dhan scrip master the daily
 * re-check already uses) rather than requiring manual discovery later.
 * 120 of 498 backtestable symbols qualified.
 *
 * Still a static snapshot between runs, not a live recompute — re-run
 * this script quarterly, or after any change to the swing entry rules
 * in screening-engine.ts. Review the generated diff before committing,
 * same as any other code change.
 */
export const SWING_PROVEN_SYMBOLS = new Set([
  'IRFC', 'RPOWER', 'TATAELXSI', 'ANANDRATHI', 'ATGL',
  'TTML', 'PATANJALI', 'RAILTEL', 'ADANIPOWER', 'ADANIGREEN',
  'DIXON', 'RVNL', 'KAJARIACER', 'PNBHOUSING', 'POONAWALLA',
  'INDIANB', 'INFY', 'CHENNPETRO', 'UNIONBANK', 'ADANIENSOL',
  'TATAPOWER', 'ACE', 'TATASTEEL', 'SBIN', 'NEWGEN',
  'OLECTRA', 'AFFLE', 'MAZDOCK', 'IIFL', 'ANANTRAJ',
  'SJVN', 'TATAINVEST', 'SOLARINDS', 'PGEL', 'ZENTEC',
  'HAL', 'ELGIEQUIP', 'CYIENT', 'KFINTECH', 'CUMMINSIND',
  'TRENT', 'WOCKPHARMA', 'KALYANKJIL', 'INOXWIND', 'BLS',
  'TATACONSUM', 'ARE&M', 'WIPRO', 'DATAPATTNS', 'GPIL',
  'JSWSTEEL', 'GVT&D', 'TMPV', 'MRPL', 'INDHOTEL',
  'SUZLON', 'BHEL', 'HINDCOPPER', 'SUNDARMFIN', 'CDSL',
  'SWANCORP', 'IEX', 'GODREJPROP', 'J&KBANK', 'SPLPETRO',
  'BSE', 'BSOFT', 'GRAVITA', 'ECLERX', 'HCLTECH',
  'PNB', 'ABCAPITAL', 'FLUOROCHEM', 'TRIDENT', 'CGPOWER',
  'BALRAMCHIN', 'KIRLOSENG', 'BEL', 'NBCC', 'ONGC',
  'OIL', 'LTFOODS', 'TIINDIA', 'IOB', 'TATACHEM',
  'KPRMILL', 'SARDAEN', 'LTTS', 'JINDALSTEL', 'LAURUSLABS',
  'ANGELONE', 'TITAN', 'CHOICEIN', 'EMAMILTD', 'DEEPAKFERT',
  'FORCEMOT', 'HEG', 'JSL', 'RBLBANK', 'SYRMA',
  'GESHIP', 'PIDILITIND', 'ALKEM', 'HINDALCO', 'KPITTECH',
  'GMDCLTD', 'DIVISLAB', 'PERSISTENT', 'JWL', 'NAVINFLUOR',
  'VEDL', 'IDEA', 'GLAND', 'HONAUT', 'HBLENGINE',
  'AXISBANK', 'JINDALSAW', 'ICICIBANK', 'POWERINDIA', 'LLOYDSME',
]);

/**
 * Symbols that qualified on backtest performance but are currently
 * excluded for trading-series restrictions (auto-detected at
 * regeneration time, see symbol-series-check.ts).
 */
export const EXCLUDED_RESTRICTED_SYMBOLS: Record<string, string> = {
};

/**
 * Per-symbol real backtest metrics for the names above — same source
 * as SWING_PROVEN_SYMBOLS, just the actual numbers instead of a bare
 * name list, so the dashboard can rank/display by real backtest
 * quality instead of just listing symbols.
 */
export interface SwingProvenMetrics {
  sector: string;
  profitFactor: number;
  totalTrades: number;
  winRate: number;
  sharpeRatio: number;
  maxDrawdown: number;
}

export const SWING_PROVEN_METRICS: Record<string, SwingProvenMetrics> = {
  IRFC: { sector: 'Financial Services', profitFactor: 5.17, totalTrades: 20, winRate: 45, sharpeRatio: 1.74, maxDrawdown: 2 },
  RPOWER: { sector: 'Power', profitFactor: 4.99, totalTrades: 16, winRate: 31.3, sharpeRatio: 0.98, maxDrawdown: 3 },
  TATAELXSI: { sector: 'Information Technology', profitFactor: 4.73, totalTrades: 31, winRate: 51.6, sharpeRatio: 2.43, maxDrawdown: 2.9 },
  ANANDRATHI: { sector: 'Financial Services', profitFactor: 4.41, totalTrades: 27, winRate: 55.6, sharpeRatio: 2.28, maxDrawdown: 1.3 },
  ATGL: { sector: 'Oil Gas & Consumable Fuels', profitFactor: 4.04, totalTrades: 21, winRate: 33.3, sharpeRatio: 1.57, maxDrawdown: 2.3 },
  TTML: { sector: 'Telecommunication', profitFactor: 3.63, totalTrades: 25, winRate: 44, sharpeRatio: 1.49, maxDrawdown: 2 },
  PATANJALI: { sector: 'Fast Moving Consumer Goods', profitFactor: 3.55, totalTrades: 32, winRate: 34.4, sharpeRatio: 1.54, maxDrawdown: 2.2 },
  RAILTEL: { sector: 'Telecommunication', profitFactor: 3.52, totalTrades: 19, winRate: 47.4, sharpeRatio: 2.22, maxDrawdown: 1.3 },
  ADANIPOWER: { sector: 'Power', profitFactor: 3.51, totalTrades: 40, winRate: 42.5, sharpeRatio: 2.5, maxDrawdown: 1.9 },
  ADANIGREEN: { sector: 'Power', profitFactor: 3.36, totalTrades: 30, winRate: 40, sharpeRatio: 1.94, maxDrawdown: 2.3 },
  DIXON: { sector: 'Consumer Durables', profitFactor: 3.17, totalTrades: 41, winRate: 51.2, sharpeRatio: 2.67, maxDrawdown: 1.2 },
  RVNL: { sector: 'Construction', profitFactor: 3.12, totalTrades: 37, winRate: 40.5, sharpeRatio: 2.21, maxDrawdown: 2 },
  KAJARIACER: { sector: 'Consumer Durables', profitFactor: 3.07, totalTrades: 16, winRate: 31.3, sharpeRatio: 1.48, maxDrawdown: 0.6 },
  PNBHOUSING: { sector: 'Financial Services', profitFactor: 3.05, totalTrades: 15, winRate: 26.7, sharpeRatio: 1.03, maxDrawdown: 2.2 },
  POONAWALLA: { sector: 'Financial Services', profitFactor: 3.05, totalTrades: 38, winRate: 39.5, sharpeRatio: 1.45, maxDrawdown: 2.5 },
  INDIANB: { sector: 'Financial Services', profitFactor: 2.95, totalTrades: 16, winRate: 31.3, sharpeRatio: 1.48, maxDrawdown: 1.8 },
  INFY: { sector: 'Information Technology', profitFactor: 2.9, totalTrades: 35, winRate: 42.9, sharpeRatio: 2.21, maxDrawdown: 0.9 },
  CHENNPETRO: { sector: 'Oil Gas & Consumable Fuels', profitFactor: 2.86, totalTrades: 15, winRate: 26.7, sharpeRatio: 1.34, maxDrawdown: 2.9 },
  UNIONBANK: { sector: 'Financial Services', profitFactor: 2.85, totalTrades: 36, winRate: 41.7, sharpeRatio: 1.96, maxDrawdown: 1.6 },
  ADANIENSOL: { sector: 'Power', profitFactor: 2.81, totalTrades: 16, winRate: 31.3, sharpeRatio: 1.46, maxDrawdown: 1.5 },
  TATAPOWER: { sector: 'Power', profitFactor: 2.81, totalTrades: 35, winRate: 40, sharpeRatio: 2.03, maxDrawdown: 4.5 },
  ACE: { sector: 'Capital Goods', profitFactor: 2.8, totalTrades: 16, winRate: 31.3, sharpeRatio: 1.36, maxDrawdown: 1.6 },
  TATASTEEL: { sector: 'Metals & Mining', profitFactor: 2.79, totalTrades: 15, winRate: 26.7, sharpeRatio: 1.23, maxDrawdown: 1.5 },
  SBIN: { sector: 'Financial Services', profitFactor: 2.67, totalTrades: 38, winRate: 44.7, sharpeRatio: 2.24, maxDrawdown: 1.2 },
  NEWGEN: { sector: 'Information Technology', profitFactor: 2.65, totalTrades: 15, winRate: 26.7, sharpeRatio: 0.83, maxDrawdown: 1.8 },
  OLECTRA: { sector: 'Automobile and Auto Components', profitFactor: 2.62, totalTrades: 16, winRate: 31.3, sharpeRatio: 1.59, maxDrawdown: 1.4 },
  AFFLE: { sector: 'Information Technology', profitFactor: 2.61, totalTrades: 15, winRate: 26.7, sharpeRatio: 1.44, maxDrawdown: 2 },
  MAZDOCK: { sector: 'Capital Goods', profitFactor: 2.57, totalTrades: 30, winRate: 36.7, sharpeRatio: 1.7, maxDrawdown: 1.8 },
  IIFL: { sector: 'Financial Services', profitFactor: 2.49, totalTrades: 16, winRate: 31.3, sharpeRatio: 0.84, maxDrawdown: 3 },
  ANANTRAJ: { sector: 'Realty', profitFactor: 2.43, totalTrades: 53, winRate: 41.5, sharpeRatio: 2.38, maxDrawdown: 2.2 },
  SJVN: { sector: 'Power', profitFactor: 2.41, totalTrades: 34, winRate: 47.1, sharpeRatio: 2.44, maxDrawdown: 1.2 },
  TATAINVEST: { sector: 'Financial Services', profitFactor: 2.41, totalTrades: 18, winRate: 33.3, sharpeRatio: 1.07, maxDrawdown: 1.5 },
  SOLARINDS: { sector: 'Chemicals', profitFactor: 2.39, totalTrades: 40, winRate: 47.5, sharpeRatio: 2.5, maxDrawdown: 1.3 },
  PGEL: { sector: 'Consumer Durables', profitFactor: 2.37, totalTrades: 21, winRate: 33.3, sharpeRatio: 1.27, maxDrawdown: 2.5 },
  ZENTEC: { sector: 'Capital Goods', profitFactor: 2.37, totalTrades: 15, winRate: 26.7, sharpeRatio: 0.97, maxDrawdown: 2.5 },
  HAL: { sector: 'Capital Goods', profitFactor: 2.36, totalTrades: 42, winRate: 42.9, sharpeRatio: 2.24, maxDrawdown: 1.3 },
  ELGIEQUIP: { sector: 'Capital Goods', profitFactor: 2.32, totalTrades: 16, winRate: 31.3, sharpeRatio: 1.45, maxDrawdown: 1.5 },
  CYIENT: { sector: 'Information Technology', profitFactor: 2.31, totalTrades: 27, winRate: 48.1, sharpeRatio: 2.24, maxDrawdown: 1.4 },
  KFINTECH: { sector: 'Financial Services', profitFactor: 2.3, totalTrades: 19, winRate: 52.6, sharpeRatio: 1.63, maxDrawdown: 1.7 },
  CUMMINSIND: { sector: 'Capital Goods', profitFactor: 2.28, totalTrades: 47, winRate: 42.6, sharpeRatio: 2.5, maxDrawdown: 1.1 },
  TRENT: { sector: 'Consumer Services', profitFactor: 2.26, totalTrades: 46, winRate: 47.8, sharpeRatio: 2.57, maxDrawdown: 1.7 },
  WOCKPHARMA: { sector: 'Healthcare', profitFactor: 2.26, totalTrades: 21, winRate: 33.3, sharpeRatio: 1.33, maxDrawdown: 1.8 },
  KALYANKJIL: { sector: 'Consumer Durables', profitFactor: 2.24, totalTrades: 26, winRate: 34.6, sharpeRatio: 1.73, maxDrawdown: 2.1 },
  INOXWIND: { sector: 'Capital Goods', profitFactor: 2.23, totalTrades: 38, winRate: 47.4, sharpeRatio: 1.48, maxDrawdown: 3.1 },
  BLS: { sector: 'Consumer Services', profitFactor: 2.2, totalTrades: 41, winRate: 36.6, sharpeRatio: 1.99, maxDrawdown: 3.5 },
  TATACONSUM: { sector: 'Fast Moving Consumer Goods', profitFactor: 2.17, totalTrades: 18, winRate: 33.3, sharpeRatio: 1.28, maxDrawdown: 1 },
  'ARE&M': { sector: 'Automobile and Auto Components', profitFactor: 2.16, totalTrades: 29, winRate: 41.4, sharpeRatio: 1.89, maxDrawdown: 1.2 },
  WIPRO: { sector: 'Information Technology', profitFactor: 2.07, totalTrades: 18, winRate: 33.3, sharpeRatio: 1.3, maxDrawdown: 1.1 },
  DATAPATTNS: { sector: 'Capital Goods', profitFactor: 2.06, totalTrades: 22, winRate: 40.9, sharpeRatio: 2.19, maxDrawdown: 1.2 },
  GPIL: { sector: 'Capital Goods', profitFactor: 2.06, totalTrades: 37, winRate: 35.1, sharpeRatio: 1.75, maxDrawdown: 2.5 },
  JSWSTEEL: { sector: 'Metals & Mining', profitFactor: 2.05, totalTrades: 15, winRate: 26.7, sharpeRatio: 0.78, maxDrawdown: 1.4 },
  'GVT&D': { sector: 'Capital Goods', profitFactor: 2.05, totalTrades: 32, winRate: 34.4, sharpeRatio: 1.44, maxDrawdown: 2.3 },
  TMPV: { sector: 'Automobile and Auto Components', profitFactor: 2.04, totalTrades: 18, winRate: 33.3, sharpeRatio: 0.93, maxDrawdown: 1.8 },
  MRPL: { sector: 'Oil Gas & Consumable Fuels', profitFactor: 2.04, totalTrades: 30, winRate: 40, sharpeRatio: 1.73, maxDrawdown: 2.6 },
  INDHOTEL: { sector: 'Consumer Services', profitFactor: 2, totalTrades: 35, winRate: 34.3, sharpeRatio: 2.07, maxDrawdown: 1.5 },
  SUZLON: { sector: 'Capital Goods', profitFactor: 2, totalTrades: 36, winRate: 41.7, sharpeRatio: 1.68, maxDrawdown: 2.6 },
  BHEL: { sector: 'Capital Goods', profitFactor: 1.99, totalTrades: 34, winRate: 41.2, sharpeRatio: 1.87, maxDrawdown: 1.6 },
  HINDCOPPER: { sector: 'Metals & Mining', profitFactor: 1.99, totalTrades: 16, winRate: 31.3, sharpeRatio: 0.93, maxDrawdown: 4.5 },
  SUNDARMFIN: { sector: 'Financial Services', profitFactor: 1.98, totalTrades: 16, winRate: 31.3, sharpeRatio: 1.01, maxDrawdown: 1 },
  CDSL: { sector: 'Financial Services', profitFactor: 1.97, totalTrades: 16, winRate: 31.3, sharpeRatio: 1.21, maxDrawdown: 1.7 },
  SWANCORP: { sector: 'Chemicals', profitFactor: 1.97, totalTrades: 15, winRate: 26.7, sharpeRatio: 0.89, maxDrawdown: 2.4 },
  IEX: { sector: 'Financial Services', profitFactor: 1.96, totalTrades: 31, winRate: 41.9, sharpeRatio: 1.79, maxDrawdown: 2 },
  GODREJPROP: { sector: 'Realty', profitFactor: 1.94, totalTrades: 16, winRate: 25, sharpeRatio: 0.95, maxDrawdown: 1.3 },
  'J&KBANK': { sector: 'Financial Services', profitFactor: 1.94, totalTrades: 26, winRate: 34.6, sharpeRatio: 1.76, maxDrawdown: 2 },
  SPLPETRO: { sector: 'Chemicals', profitFactor: 1.93, totalTrades: 16, winRate: 31.3, sharpeRatio: 0.91, maxDrawdown: 1.5 },
  BSE: { sector: 'Financial Services', profitFactor: 1.9, totalTrades: 18, winRate: 33.3, sharpeRatio: 1.15, maxDrawdown: 1.8 },
  BSOFT: { sector: 'Information Technology', profitFactor: 1.89, totalTrades: 15, winRate: 20, sharpeRatio: 0.91, maxDrawdown: 2.3 },
  GRAVITA: { sector: 'Metals & Mining', profitFactor: 1.89, totalTrades: 15, winRate: 26.7, sharpeRatio: 1.04, maxDrawdown: 1.7 },
  ECLERX: { sector: 'Services', profitFactor: 1.89, totalTrades: 40, winRate: 40, sharpeRatio: 1.38, maxDrawdown: 2.7 },
  HCLTECH: { sector: 'Information Technology', profitFactor: 1.87, totalTrades: 42, winRate: 45.2, sharpeRatio: 2.01, maxDrawdown: 1 },
  PNB: { sector: 'Financial Services', profitFactor: 1.87, totalTrades: 35, winRate: 48.6, sharpeRatio: 1.84, maxDrawdown: 2.3 },
  ABCAPITAL: { sector: 'Financial Services', profitFactor: 1.86, totalTrades: 15, winRate: 26.7, sharpeRatio: 0.95, maxDrawdown: 1.2 },
  FLUOROCHEM: { sector: 'Chemicals', profitFactor: 1.83, totalTrades: 15, winRate: 26.7, sharpeRatio: 1.31, maxDrawdown: 1.3 },
  TRIDENT: { sector: 'Textiles', profitFactor: 1.83, totalTrades: 27, winRate: 40.7, sharpeRatio: 1.69, maxDrawdown: 2.6 },
  CGPOWER: { sector: 'Capital Goods', profitFactor: 1.82, totalTrades: 50, winRate: 36, sharpeRatio: 2.07, maxDrawdown: 1.5 },
  BALRAMCHIN: { sector: 'Fast Moving Consumer Goods', profitFactor: 1.82, totalTrades: 15, winRate: 26.7, sharpeRatio: 1.11, maxDrawdown: 1.4 },
  KIRLOSENG: { sector: 'Capital Goods', profitFactor: 1.82, totalTrades: 49, winRate: 40.8, sharpeRatio: 1.96, maxDrawdown: 2.2 },
  BEL: { sector: 'Capital Goods', profitFactor: 1.81, totalTrades: 49, winRate: 38.8, sharpeRatio: 2.09, maxDrawdown: 1.5 },
  NBCC: { sector: 'Construction', profitFactor: 1.8, totalTrades: 35, winRate: 34.3, sharpeRatio: 1.54, maxDrawdown: 3.3 },
  ONGC: { sector: 'Oil Gas & Consumable Fuels', profitFactor: 1.78, totalTrades: 16, winRate: 31.3, sharpeRatio: 0.93, maxDrawdown: 1.5 },
  OIL: { sector: 'Oil Gas & Consumable Fuels', profitFactor: 1.78, totalTrades: 45, winRate: 35.6, sharpeRatio: 2.15, maxDrawdown: 2.1 },
  LTFOODS: { sector: 'Fast Moving Consumer Goods', profitFactor: 1.75, totalTrades: 15, winRate: 26.7, sharpeRatio: 0.89, maxDrawdown: 2.5 },
  TIINDIA: { sector: 'Automobile and Auto Components', profitFactor: 1.73, totalTrades: 15, winRate: 26.7, sharpeRatio: 0.99, maxDrawdown: 1.1 },
  IOB: { sector: 'Financial Services', profitFactor: 1.73, totalTrades: 34, winRate: 44.1, sharpeRatio: 1.76, maxDrawdown: 2.7 },
  TATACHEM: { sector: 'Chemicals', profitFactor: 1.71, totalTrades: 15, winRate: 26.7, sharpeRatio: 0.79, maxDrawdown: 1.4 },
  KPRMILL: { sector: 'Textiles', profitFactor: 1.67, totalTrades: 26, winRate: 34.6, sharpeRatio: 1.37, maxDrawdown: 1.5 },
  SARDAEN: { sector: 'Metals & Mining', profitFactor: 1.67, totalTrades: 54, winRate: 38.9, sharpeRatio: 2.2, maxDrawdown: 2 },
  LTTS: { sector: 'Information Technology', profitFactor: 1.65, totalTrades: 18, winRate: 33.3, sharpeRatio: 0.86, maxDrawdown: 1.7 },
  JINDALSTEL: { sector: 'Metals & Mining', profitFactor: 1.64, totalTrades: 37, winRate: 35.1, sharpeRatio: 1.89, maxDrawdown: 1.9 },
  LAURUSLABS: { sector: 'Healthcare', profitFactor: 1.64, totalTrades: 45, winRate: 48.9, sharpeRatio: 2.25, maxDrawdown: 1.9 },
  ANGELONE: { sector: 'Financial Services', profitFactor: 1.64, totalTrades: 29, winRate: 44.8, sharpeRatio: 1.56, maxDrawdown: 1.5 },
  TITAN: { sector: 'Consumer Durables', profitFactor: 1.63, totalTrades: 21, winRate: 33.3, sharpeRatio: 1.11, maxDrawdown: 1.3 },
  CHOICEIN: { sector: 'Financial Services', profitFactor: 1.61, totalTrades: 26, winRate: 34.6, sharpeRatio: 1.63, maxDrawdown: 0.9 },
  EMAMILTD: { sector: 'Fast Moving Consumer Goods', profitFactor: 1.61, totalTrades: 15, winRate: 26.7, sharpeRatio: 0.92, maxDrawdown: 1.3 },
  DEEPAKFERT: { sector: 'Chemicals', profitFactor: 1.59, totalTrades: 15, winRate: 26.7, sharpeRatio: 0.91, maxDrawdown: 2.5 },
  FORCEMOT: { sector: 'Automobile and Auto Components', profitFactor: 1.59, totalTrades: 15, winRate: 26.7, sharpeRatio: 0.97, maxDrawdown: 1.7 },
  HEG: { sector: 'Capital Goods', profitFactor: 1.59, totalTrades: 15, winRate: 26.7, sharpeRatio: 0.89, maxDrawdown: 3.1 },
  JSL: { sector: 'Metals & Mining', profitFactor: 1.57, totalTrades: 16, winRate: 31.3, sharpeRatio: 1.08, maxDrawdown: 1.6 },
  RBLBANK: { sector: 'Financial Services', profitFactor: 1.57, totalTrades: 33, winRate: 45.5, sharpeRatio: 1.83, maxDrawdown: 2.1 },
  SYRMA: { sector: 'Capital Goods', profitFactor: 1.57, totalTrades: 15, winRate: 26.7, sharpeRatio: 0.91, maxDrawdown: 1.5 },
  GESHIP: { sector: 'Services', profitFactor: 1.56, totalTrades: 18, winRate: 33.3, sharpeRatio: 1.02, maxDrawdown: 1.3 },
  PIDILITIND: { sector: 'Chemicals', profitFactor: 1.55, totalTrades: 26, winRate: 34.6, sharpeRatio: 1.44, maxDrawdown: 1.2 },
  ALKEM: { sector: 'Healthcare', profitFactor: 1.54, totalTrades: 35, winRate: 37.1, sharpeRatio: 1.33, maxDrawdown: 1.4 },
  HINDALCO: { sector: 'Metals & Mining', profitFactor: 1.52, totalTrades: 43, winRate: 34.9, sharpeRatio: 1.73, maxDrawdown: 1.9 },
  KPITTECH: { sector: 'Information Technology', profitFactor: 1.52, totalTrades: 21, winRate: 33.3, sharpeRatio: 1.09, maxDrawdown: 2.5 },
  GMDCLTD: { sector: 'Metals & Mining', profitFactor: 1.52, totalTrades: 37, winRate: 37.8, sharpeRatio: 1.25, maxDrawdown: 2 },
  DIVISLAB: { sector: 'Healthcare', profitFactor: 1.51, totalTrades: 24, winRate: 33.3, sharpeRatio: 1.01, maxDrawdown: 1.1 },
  PERSISTENT: { sector: 'Information Technology', profitFactor: 1.51, totalTrades: 48, winRate: 35.4, sharpeRatio: 2.01, maxDrawdown: 1.1 },
  JWL: { sector: 'Capital Goods', profitFactor: 1.48, totalTrades: 40, winRate: 42.5, sharpeRatio: 1.84, maxDrawdown: 2.6 },
  NAVINFLUOR: { sector: 'Chemicals', profitFactor: 1.47, totalTrades: 16, winRate: 31.3, sharpeRatio: 1.15, maxDrawdown: 2 },
  VEDL: { sector: 'Metals & Mining', profitFactor: 1.46, totalTrades: 36, winRate: 38.9, sharpeRatio: 1.16, maxDrawdown: 4.2 },
  IDEA: { sector: 'Telecommunication', profitFactor: 1.46, totalTrades: 21, winRate: 33.3, sharpeRatio: 0.91, maxDrawdown: 2.4 },
  GLAND: { sector: 'Healthcare', profitFactor: 1.46, totalTrades: 15, winRate: 46.7, sharpeRatio: 1.14, maxDrawdown: 1.4 },
  HONAUT: { sector: 'Capital Goods', profitFactor: 1.45, totalTrades: 17, winRate: 41.2, sharpeRatio: 1.3, maxDrawdown: 4.3 },
  HBLENGINE: { sector: 'Capital Goods', profitFactor: 1.45, totalTrades: 16, winRate: 31.3, sharpeRatio: 0.93, maxDrawdown: 1.9 },
  AXISBANK: { sector: 'Financial Services', profitFactor: 1.44, totalTrades: 21, winRate: 33.3, sharpeRatio: 1.2, maxDrawdown: 0.8 },
  JINDALSAW: { sector: 'Capital Goods', profitFactor: 1.42, totalTrades: 35, winRate: 37.1, sharpeRatio: 1.27, maxDrawdown: 2.7 },
  ICICIBANK: { sector: 'Financial Services', profitFactor: 1.41, totalTrades: 18, winRate: 33.3, sharpeRatio: 0.85, maxDrawdown: 1 },
  POWERINDIA: { sector: 'Capital Goods', profitFactor: 1.41, totalTrades: 21, winRate: 33.3, sharpeRatio: 1.17, maxDrawdown: 2.1 },
  LLOYDSME: { sector: 'Metals & Mining', profitFactor: 1.41, totalTrades: 15, winRate: 13.3, sharpeRatio: 0.68, maxDrawdown: 1.4 },
};
